version: "3.4"

services:

  testclient:
    build:
      context: .
      dockerfile: Dockerfile.app
    networks:
      - transit_ttyd
    ports:
      - 5000:5000


networks:
  transit_ttyd:
    external: true

